// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzsxzwvxivqbczvczytm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6c3h6d3Z4aXZxYmN6dmN6eXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NzQ1MzEsImV4cCI6MjA1NzM1MDUzMX0.-F0S0DRbOOp6YTcnF6QOvV7PiqX6dIEn5usIeD8BO2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);